/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class allogen_example_ExampleClass */

#ifndef _Included_allogen_example_ExampleClass
#define _Included_allogen_example_ExampleClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     allogen_example_ExampleClass
 * Method:    _init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_allogen_example_ExampleClass__1init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_allogen_example_ExampleClass__1init__
  (JNIEnv *, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_finalize
  (JNIEnv *, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    setInteger
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_setInteger
  (JNIEnv *, jobject, jint);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    getInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_allogen_example_ExampleClass_getInteger
  (JNIEnv *, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    copy
 * Signature: ()Lallogen/example/ExampleClass;
 */
JNIEXPORT jobject JNICALL Java_allogen_example_ExampleClass_copy
  (JNIEnv *, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    doAsync
 * Signature: (Lallogen/example/AsyncTaskCallback;)V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_doAsync
  (JNIEnv *, jobject, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    anotherCallback
 * Signature: (Lallogen/example/AsyncTaskCallback2;)I
 */
JNIEXPORT jint JNICALL Java_allogen_example_ExampleClass_anotherCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    virtualCallback
 * Signature: (Lallogen/example/AsyncTaskCallback2;II)I
 */
JNIEXPORT jint JNICALL Java_allogen_example_ExampleClass_virtualCallback
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    createAnother
 * Signature: (Ljava/lang/String;)Lallogen/example/AnotherClass;
 */
JNIEXPORT jobject JNICALL Java_allogen_example_ExampleClass_createAnother
  (JNIEnv *, jobject, jstring);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    createAnotherAsync
 * Signature: (Ljava/lang/String;Lallogen/example/CreateAnotherAsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_createAnotherAsync
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     allogen_example_ExampleClass
 * Method:    printAnother
 * Signature: (Lallogen/example/AnotherClass;)V
 */
JNIEXPORT void JNICALL Java_allogen_example_ExampleClass_printAnother
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
